remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-prism
title: Unity AIを使ってみよう！はじめてのAssistant&Generatorsサポートページ
description: 技術書典19で発売した新刊のサポートページです。
show_downloads: [false]
prism:
  plugins:
    - copy-to-clipboard
    - toolbar
